### ISSUE TITLE
When service quits fast, "swarm start" keeps running forever.

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#10]
Here is an app with one ubuntu component that only mounts a volume and executes the `mount` command. `swarm start` for this app never finishes, it never leaves the "starting" status.

```
{
    "app_name": "volume-mounter",
    "services": [
        {
            "service_name": "volume-mounter",
            "components": [
                {
                    "component_name": "ubuntu",
                    "image": "ubuntu",
                    "args": ["mount"],
                    "volumes": [
                        {"path": "/mnt/vol1", "size": "1 GB"}
                    ]
                }
            ]
        }
    ]
}
```

As the logs show, the command is executed just fine.

I would expect some status like "finished" or "stopped" at the end. At least `swarm up` and `swarm start` should be done at some point.

Original Author: @marian
Created at 18-01-2015 08:13:01
Gitlab: [giantswarm/cli!237](https://git.giantswarm.io/giantswarm/cli/issues/237)

**Comment by marians** [comment]
I re-tested this, now that `swarm start` is an asynchronous operation. The result was still not satisfactory.

The command exited after 4 minutes with this output:

```
Starting service 'fast-finisher'…
Waiting for 'fast-finisher' to get started…
| 
```

I tested on aws-alpha.

**Comment by marians** [comment]
The situation should already improve here if tasks fail quicker.
https://github.com/giantswarm/giantswarm/issues/381

**Comment by marians** [comment]
Plan: Retest this and record task details. Then check if we can make better use of details in the CLI or need to provide more details by the appservice.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
