### ISSUE TITLE
Remove busy-wait loop in start/stop when app-service provided endpoint for it.

### ISSUE THREAD

**Issue by ewoutp** [giantswarm/cli#151]
Remove the busy-wait loop in utils.go#waitForStatus when:

- the app-service provides an api for "wait for start/stop to complete" or 
- the app-service does a better job at differentiating between failed because of a failed start and failed because of "was failed before but has not started yet" 

See also #138

**Comment by marians** [comment]
@ewoutp Is this problem solved by using the asynchronous task?

**Comment by ewoutp** [comment]
We can now cleanup the CLI (and remove this busywait loop).
But that cleanup still has to be done.
