### ISSUE TITLE
List (and set) environment variables

### ISSUE THREAD

**Issue by luebken** [giantswarm/cli#155]
Configuration and mis-configuration of environment variables is a common cause for problems. We should give the user means to solve investigate and solve these problems.

e.g. list environment variables:
- `swarm vars <instance-id>`: list all environment variables available to this instance
  A first simple version could be showing them in the logs when a container is started.

In addition we might give the user the means to change them: 
- `swarm vars  <instance-id> set XXX=value`: set an environment variable

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
