### ISSUE TITLE
swarm.json: make ports in links optional

### ISSUE THREAD

**Issue by luebken** [giantswarm/cli#156]
We are using Docker links to connect two components (via ambassadors) together. To connect a dependent component a user needs to specify the container-name and port. 

When linking Docker containers locally you don't need to specify any ports. They are made available based on the exposed port. See: https://docs.docker.com/userguide/dockerlinks/

We are using this in our examples e.g. https://github.com/giantswarm/giantswarm-firstapp-nodejs/blob/master/Makefile#L13

Why does the user need to specify a port in the swarm.json?

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
