### ISSUE TITLE
EOF error on swarm start (actually on getting status)

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#163]
This just happened after `swarm start` for helloworld:

```
Get https://api.giantswarm.io/v1/company/marians-bot/env/dev/app/helloworld/status: EOF
```

The command quitted with an error, not starting the app.

**Comment by ewoutp** [comment]
With the launch of CLI 0.22 this has not been reported afaik.
Closing this now. If the problem re-appears, let's open another issue
