### ISSUE TITLE
1 click feedback and swarm wtf

### ISSUE THREAD

**Issue by luebken** [giantswarm/cli#170]
Our CLI is the primary user interface. We need to build easy ways for our users to communicate with us.

Two ideas:

* *1 click feedback* when something unusual happens like CLI or API error. give the users the chance to send feedback with a simple "y". afterwards the user can be asked if he wants to provide additional feedback. the idea here is to hook him with a 1-click feedback and later get him to provide more
  
* *swarm wtf* to do the above in any situation. swarm wtf sends the current context to support. in addition the user can provide a message.

**Comment by ZeissS** [comment]
@luebken We took the liberty to move this to Later as we felt you don't actually work on this anymore :P

**Comment by zeisss** [comment]
lets close this for now.
