### ISSUE TITLE
Add truncating of columnized output ("swarm ls", "swarm status")

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#19]
Some commands grow and grow in the number of columns and the width of columns.

There should be a generic way to truncate this.

Original Author: @ewout
Created at 09-01-2015 15:50:47
Gitlab: [giantswarm/cli!220](https://git.giantswarm.io/giantswarm/cli/issues/220)

**Comment by marians** [comment]
We have this for the image, also instance IDs became shorter.
