### ISSUE TITLE
Show warning if variable is not resolved

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#21]
If a variable could not be resolved during the creation of application, the creation should be aborted or the user warned. 

Original Author: @luebken
Created at 06-01-2015 10:48:40
Gitlab: [giantswarm/cli!217](https://git.giantswarm.io/giantswarm/cli/issues/217)

**Comment by marians** [comment]
Problem: unresolved variables are hard to detect. Possible solution: Warn about every string containing a `$` sign. This might lead to false warnings.

We'll try this and see what user feedback we get. We might then provide a way to suppress the warning.

**Comment by marians** [comment]
Related: https://github.com/giantswarm/cli/issues/47 describes a special case where a variables file is used, but no key is available for the current environment. This should be handled with a specific message.

**Comment by JosephSalisbury** [comment]
https://github.com/giantswarm/cli/pull/491

ping @giantswarm/team-features

**Comment by ewoutp** [comment]
@JosephSalisbury Please ping people for review in the PR, not in the issue where you reference a PR.

**Comment by JosephSalisbury** [comment]
Was fixed in #491, but changes to validation has re-opened

**Comment by ZeissS** [comment]
@JosephSalisbury whats the status here exactly?

**Comment by JosephSalisbury** [comment]
was working, is not working now

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
