### ISSUE TITLE
Discuss Application Configuration Management Features 

### ISSUE THREAD

**Issue by kordless** [giantswarm/cli#240]
This is a discussion on proposed application configuration management features to include inside the CLI. This ticket has no output other than the discussion occurring here on Github and the subsequent tickets created from decisions to move forward with the effort.
### Intent

A comment from @teemow on #slack summarizes this ticket: _It would be good if we can get rid of those Makefiles soonish._ We currently use Makefiles in a significant portion of the user-referenced repositories we maintain on Github. These makefiles provide a way to manage the build and deployment of the applications, as `make` was intended.

Given our desire to streamline the process and make building applications with Giant Swarm (and Docker) more approachable for users, the removal of any non-critical files from an application template (proposed to be called 'formations') makes sense.
### Actions and Assets

For reference, here is a brief list of actions a user may conduct while developing and deploying an application on Giant Swarm:
- local development on a set of files in a directory
- usage of one or more Dockerfiles, either authored by user or borrowed from other locations
- create and manage directories containing one or more service images used by an application ( [see the ghost repo and sub-directory for varnish](https://github.com/giantswarm/ghost-formation/) )
- creation and modification of a `swarm.json` file in the directory
- adding variables to be used by a build script and/or swarm.json file ( see [example vars](https://github.com/giantswarm/ghost-formation/blob/master/Makefile#L32-L78) )
- creating and running a build script to build images
- creating and running a post-launch script for the container(s) to run after booting
- uploading images to Giant Swarm's image registry
- deploying an application to Giant Swarm's service
- starting an application once it has been deployed
- updating an application already running on Giant Swarm's service

An example of a current application/formation directory follows:
- Makefile
- Dockerfile
- swarm.json
- swarmvars.json
- entrypoint.sh
- docker-compose.yaml
- README.md
- application files
- application directories
- service container modules (linked github repos)

Requirements for utilizing these files includes:
- docker and/or boot2docker
- swarm CLI
- docker-compose
- make
### Feature Proposal

The 'features' listed here are designed to start a conversation. These are features that _could_ be added to the `swarm` CLI to achieve the inteded result of streamlining the creation, build, deployment and _sharing_ of applicatons on Giant Swarm:
- `swarm clone <github_repo>` - alias `git clone` + `swarm make`, clones repo and builds necessary asset(s) using swarm account and org information, where needed. The make portion will recursively utilize git sub-modules.
- `swarm make <type> <formation.json>` - builds configuration assets for the given file type, which includes `.json` (swarm.json/swarmvars.json), `.yaml` (docker-compose), Dockerfile, etc.
- `swarm local` - launches the application locally for preview. See [equivelent makefile command](https://github.com/giantswarm/ghost-formation/blob/master/Makefile#L30-L51).
- `swarm push` - uploads the set of service images required to launch the application on Giant Swarm
- `swarm publish` - uploads the repository to be shared with others.

This feature list will be modified as comments and agreements about the needed features are made.
### Assets After New Features

After these features are implimented, the following assets would be required by the application:
- formation.json
- application files
- application directories
- sub-module links
- README.md
### Requirements After New Features
- docker and/or boot2docker
- swarm CLI

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
