### ISSUE TITLE
Bash completion for dynamic data (service/component...)

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#26]
Expand bash completion to include:
- Optional arguments (-xyz)
- App/service/component/instance names/ids

Original Author: @ewout
Created at 19-12-2014 19:15:58
Gitlab: [giantswarm/cli!208](https://git.giantswarm.io/giantswarm/cli/issues/208)

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
