### ISSUE TITLE
Add a --no-local-verify option to skip local parsing

### ISSUE THREAD

**Issue by zeisss** [giantswarm/cli#260]
Currently we are parsing the swarm.json format in the client as well, which can lead to problems if your are developing new fields and need to constantly update the cli while actually working on the server.

A flag to skip this CLI validation would be nice.

I don't think this would be a user benefiting feature.

**Comment by marians** [comment]
@ZeissS After our discussion of today, I'd prefer to remove the local validation completely.

**Comment by ZeissS** [comment]
afaik there is another issue with the same topic where we more or less voted on removing it completly as well.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
