### ISSUE TITLE
Misspelled update strategy should create helpful error message

### ISSUE THREAD

**Issue by puja108** [giantswarm/cli#274]
When a user (me) tries to use an update strategy that is not there or has a typo in the update strategy the CLI only gives a strange server error. It seems there's no validation for strategy names.

Example (I mistakenly added a `-` to the strategy):

```
swarm update -s -hot-swap docs/content-master/content
Updating component 'docs/content-master/content' with version 'latest' and strategy '-hot-swap'...
/ Unknown server error: error-id: M9AXG/m0kel
Please try again in a moment.

If the problem remains, please contact us at support@giantswarm.io.
```

ping @hectorj2f

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
