### ISSUE TITLE
`swarm update` should give more verbose progress information

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#278]
The webclient polls an app's status every 10 seconds, but it seems to pick up a status change of an instance faster than the CLI when executing a `swarm update` through the CLI.

The video shows that the webclient is updated 9 seconds before the CLI finishes (1:24).

https://www.dropbox.com/s/tiu9kh1n4d0mvn2/swarm_update_web_cli_blog_1.mp4?dl=0

What is the CLI doing at the end that makes it take longer?

**Comment by ZeissS** [comment]
The client is doing multiple checks, to confirm that an instance stays up. We had the pattern in the past that stuff is reported as up, and 1sec later the user container dies because there is a startup bug in it somewhere.

**Comment by marians** [comment]
At some point, we will need proper progress output for `swarm update` then, as specced in https://github.com/giantswarm/cli/issues/4 for `swarm start`. Will rename this issue.

**Comment by ZeissS** [comment]
Please contact @ewoutp about this, as he is currently working on the task api and splitting up the "update" into smaller tasks. If you have special requirements from the cli, it can be incorporated there.

**Comment by marians** [comment]
So far I don't have specific specs for a `swarm update` progress. @ewoutp Looking at https://github.com/giantswarm/cli/issues/4#issuecomment-117070123 should give you an idea.

**Comment by ewoutp** [comment]
I think the task api will get you a lot closer to that goal.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
