### ISSUE TITLE
Login fails if user uses a certain password (character set?)

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#3]
As reported by user `l*****`, when signing up with a specific password, logging in isn't possible.

The password in question:

    <redacted>

I could already reproduce the error.

Adding @zeisss to the discussion.

Original Author: @marian
Created at 05-01-2015 08:22:13
Gitlab: [giantswarm/cli!214](https://git.giantswarm.io/giantswarm/cli/issues/214)

**Comment by marians** [comment]
@webwurst Have we seen this issue recently?

I think we could try to reproduce this with a worst case test string. Labelling backlog.

**Comment by webwurst** [comment]
@marians I haven't seen this issue.

**Comment by marians** [comment]
OK, in other words: @webwurst Have you recently heard of problems of this kind?

**Comment by webwurst** [comment]
No sorry, I also didn't hear about something like this ;)

**Comment by marians** [comment]
Closing this since no longer reproducible. Tracking related things in https://github.com/giantswarm/giantswarm/issues/393
