### ISSUE TITLE
Date/time filtering for `swarm logs`

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#30]
A story I have had several times recently and which is probably rather common for logs is this one:

> As a user I want to look at a part of my logs which cover a certain time span.

Or, slightly different:

> As a user I want to look at a part of my logs which contain a specific point in time, plus/minus a bit.

Currently I help myself by piping to something like `grep "2014-12-12T11:04". But this requires the client to pull the entire logs content via the network. And it gives me a filter granularity of an entire hour, a minute or a second.

As a first draft, this might be a straightforward way to express an exact time interval:

```
$ swarm logs <instance_id> -t 2014-12-12T11:03-2014-12-12T11:05
```

How about this for the second story?

```
#11:04:00 plus/minus 10 seconds
$ swarm logs <instance_id> -t 2014-12-12T11:04:00/10s

#11:04:00 plus/minus one minute
$ swarm logs <instance_id> -t 2014-12-12T11:04:00/1m

#11:00:00 plus/minus 1 hour
$ swarm logs <instance_id> -t 2014-12-12T11:00:00/1h
```
- Are there any CLI tools which have solved this elegantly?
- How would this interfere with the `-t` switch?

Original Author: @marian
Created at 13-12-2014 13:13:50
Gitlab: [giantswarm/cli!187](https://git.giantswarm.io/giantswarm/cli/issues/187)

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
