### ISSUE TITLE
`swarm ls <app>` do display its components/nodes

### ISSUE THREAD

**Issue by ewoutp** [giantswarm/cli#323]
Applications are becoming more complex and especially with V2 apps we're adding support on all nodes.

I think it will therefore be helpful to have an `swarm ls <app>` that lists all elements (components|nodes) of that app.

Output can be something like:

```
$ swarm ls myV1app
2 components available in application 'myV1app':

service   component       status
serviceA  compX           up
serviceA  compY           up

$ swarm ls myV2app
2 nodes available in application 'myV2app':

node           status
serviceA/nodeX up
serviceA/nodeY up
```

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
