### ISSUE TITLE
Username "Kaffeefleck" contains uppercase letter

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#33]
To match our policy, this name should be changed to lowercase.

* User ID: 54010b36-fb0b-4d58-9615-d72f3654a046
* Owner: Michael Contento
* https://app.hubspot.com/contacts/430224/contact/1350/

ping @luebken 

Original Author: @marian
Created at 12-12-2014 09:33:07
Gitlab: [giantswarm/cli!183](https://git.giantswarm.io/giantswarm/cli/issues/183)

**Comment by marians** [comment]
Closed for https://github.com/giantswarm/giantswarm/issues/384
