### ISSUE TITLE
Update int-tests/apps to V2

### ISSUE THREAD

**Issue by ewoutp** [giantswarm/cli#335]
All apps used in `make int-tests` are now in V1 format.
We should convert that to V2.

**Comment by marians** [comment]
@ewoutp Is that still valid? Feel free to close if not.

**Comment by ewoutp** [comment]
This still applies to some of the apps.
They are apparently not used, we need to update these tests.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
