### ISSUE TITLE
Cli doesn't work without internet anymore

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#336]
Validation tlds via iana let the client hang if there is no internet connection. This is bad for demos and working in trains/planes.

We should either fail fast (without an error msg - this is bad for a demo) or remove the iana check completely and update the list of tlds on each release.

**Comment by marians** [comment]
In the current version, the CLI only fails if commands do need and internet connection and don#t have one, like with `swarm version`.

    Get https://downloads.giantswarm.io/swarm/clients/VERSION: dial tcp: stat /etc/resolv.conf: no such file or directory

@teemow Can we close this?
