### ISSUE TITLE
swarm start and swarm up should report an exitcode != 0 if startup failed

### ISSUE THREAD

**Issue by zeisss** [giantswarm/cli#345]
Feedback from Neofonie and important for automation. When using `swarm up` and `swarm start` the exitcode should indicate whether the startup was successfull.

Looking at `up.go` I can see that `Quitf` is called if `create` fails. But `waitForStatus()` does not trigger it, if the startup was unsuccessful.

**Comment by marians** [comment]
@ZeissS @ewoutp Maybe it's time to revisit this after re-implementation of `start` in an async way.

I just checked this with a simple service. Here, the exitcode was 1 as expected with a failed start.

```
$ swarm start
Starting service 'fast-finisher'…
Waiting for 'fast-finisher' to get started…
\ 
⌁ [marian:~/git/support/fastexit] 4m2s 1 $ echo $?
1
```

The service definition (with a component that currently [can't be started](https://github.com/giantswarm/giantswarm/issues/181#issuecomment-153096637)):

```
{
    "name": "fast-finisher",
    "components": {
        "fast-finisher": {
            "image": "ubuntu",
            "entrypoint": "sleep 350"
        }
    }
}
```

**Comment by ewoutp** [comment]
Added this service to test-apps, see https://github.com/giantswarm/test-apps/pull/28

**Comment by zyndiecate** [comment]
Can we close this issue? Seems to be solved.

**Comment by ewoutp** [comment]
I'm not sure it is solved in all cases. 
I suggest that we cleanup the CLI (remove all remaining sync code leftovers) and check this in the process.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
