### ISSUE TITLE
Cannot start service because service not found

### ISSUE THREAD

**Issue by ZeissS** [giantswarm/cli#358]
Created by @kordless, moved from https://github.com/giantswarm/giantswarm/issues/201

swarm version 0.18.3+git, build 9c37171b7d

I've occasionally seen situations where an application is noted as 'created' but when it is started, is 'not found'. This has occurred on a remote system (Wercker) running the CLI (from a container) where the CLI reported that it created the application (showing the spinner) and then erroring out saying the application was not found. A similar failed run was noted on my desktop recently:

```
superman:python-flask-helloworld kord$ swarm --debug=true up
DEBUG: GET https://api.giantswarm.io/v1/org/kord/env/dev/service/helloworld/status
DEBUG: << 400 Bad Request
Creating 'helloworld' in the 'kord/dev' environment...
DEBUG: POST https://api.giantswarm.io/v1/org/kord/env/dev/service/ (application/json)
DEBUG: << 200 OK
Service created successfully!
Starting service helloworld...
DEBUG: POST https://api.giantswarm.io/v1/org/kord/env/dev/service/helloworld/start ()
DEBUG: << 400 Bad Request
Cannot start service. Service (helloworld) not found.
If you intend to start a new service, please create it first using either:

   swarm create [options]
   swarm up [options]

```

Application definition:
```
 "name": "helloworld",
    "components": {
      "webserver": {
        "image": "registry.giantswarm.io/kord/helloworld",
        "ports": [
          5000
        ],
        "domains": {
          "apidocsdemo.gigantic.io": 5000
        }
      }
    }
```

**Comment by zyndiecate** [comment]
This was probably due to consistency issues within out storage backend. Since we do quorum reads against etcd this should be fixed. I would consider this issue to be solved. Just closing.
