### ISSUE TITLE
swarm.json validation offers not enough context

### ISSUE THREAD

**Issue by puja108** [giantswarm/cli#363]
Currently, the error message after validation of swarm.jsonhas failed can look something like

Cannot create your service due to a syntax error in 'swarm.json'
Please check the file near the marked position:

```
  },
  ^
```

, which can be really hard to find and correct.

I could think of two solutions (that could actually both be applied together for even better UX):
1. Include line number
2. Include previous and following line

@marians gave a +1

**Comment by puja108** [comment]
More users have +1ed this recently. One of them suggested using https://atom.io/packages/jsonlint as a current workaround as it help with fixing JSON syntax.

**Comment by luebken** [comment]
I like it. Why is JSONlint a workaround?

**Comment by puja108** [comment]
As the actual issue is that we don't provide enough context around our JSON validation error message. Sure we can recommend the user to use JSONlint in his favorite editor (thinking about how currently), but that still doesn't fix our error message itself.

**Comment by marians** [comment]
How about integrating JSONlint-like behaviour and syntax-level checking before the more semantical validation?

**Comment by puja108** [comment]
yeah, isn't JSONlint an open library anyway?

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
