### ISSUE TITLE
include a docker image with our swarm CLI in the release process

### ISSUE THREAD

**Issue by puja108** [giantswarm/cli#364]
We could create a docker image that includes our latest swarm CLI, so someone who has docker installed could use swarm without even installing the CLI.

Our last iteration came up with a minimal image like follwing:

```
FROM scratch
COPY ca-certificates.crt /etc/ssl/certs/
COPY swarm /usr/local/bin/
ENTRYPOINT ["swarm"]
```

@webwurst and @marians gave input on this before

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
