### ISSUE TITLE
"swarm update" usually results in exit with EOF

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#366]
When doing a `swarm update` on some component, the result is usually this:

```
Updating component 'someservice/mycomponent' with version 'latest' and strategy 'one-by-one'...
Post https://api.giantswarm.io/v1/org/marian/env/dev/service/bad-domains/component/update: EOF
```

This seems to be related to a connection timeout after 60 seconds.

Ping @zyndiecate

**Comment by ewoutp** [comment]
See giantswarm/giantswarm#242

**Comment by zyndiecate** [comment]
EOF on component updates are fixed by https://github.com/giantswarm/cli/pull/451
