### ISSUE TITLE
"swarm start" needs error message for multiple failed instances

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#367]
Currently the error displayed when starting a service fails looks like this:

```
Starting service unexposed-port...
Service unexposed-port is failed.

The following components failed to start
mycomponent  Show logs with: swarm logs crrgwg3hkecn
```

This doesn't look so nice. We need a bit of a better layout that also works for multiple failed instances.

**Comment by marians** [comment]
I just removed the "It should look like this" part from the description. We need something that takes into account that multiple components could be failed with multiple instances each.

**Comment by marians** [comment]
Currently blocked by https://github.com/giantswarm/app-service/issues/595

**Comment by zyndiecate** [comment]
Is this issue still valid?

**Comment by marians** [comment]
Yes

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
