### ISSUE TITLE
swarm status name shows wrong message when network errors occur

### ISSUE THREAD

**Issue by zeisss** [giantswarm/cli#373]
I tried `swarm status` on a non existing service while my internet was down. I got this:

```
$ lease-swarm status ls --debug
DEBUG: request ID 'c6yt79eje8ujuhta'
Please provide a valid service or component. Use --help for details.
$
```

The network call was probably tried, but the DNS lookup failed. 

Expected
- The tried URL should be shown in the debug mode
- An error is provided to the user that the network operation failed

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
