### ISSUE TITLE
swarm update EOF error exit code is 0

### ISSUE THREAD

**Issue by ZeissS** [giantswarm/cli#384]
Neofonie reports that failed `swarm updates` have a success exit code (=0) even though the update request failed with an EOF error. To get rid of the EOF error is another issue, but we should signal errors via the exit codes clearly.

**Comment by ewoutp** [comment]
I've tried to reproduce this, but I'm getting exit code 1.

```
$ swarm update -s hot-swap notify-on-ready/box2 0.2.0
Updating component 'notify-on-ready/box2' with version '0.2.0' and strategy 'hot-swap'...
Post https://api.giantswarm.io/v1/org/ewout/env/dev/service/notify-on-ready/component/update: EOF
$ echo $?
1
```

**Comment by ZeissS** [comment]
ack, also couldn't find anything in the code. Lets close this for now.
