### ISSUE TITLE
golang image used for built is too big

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#391]
The `golang:1.4.2-cross` image is more than 2.3 GB big. I just had to pull an update which caused more than 1 GB worth of new layers to be loaded.

This can make building a pain, especially when suffering the constraints of the typical boot2docker VM volume size.

We should look for an alternative.

**Comment by ewoutp** [comment]
golang:1.5.1 is only 709MB

**Comment by marians** [comment]
Solved through https://github.com/giantswarm/cli/commit/70a16a1f8398500551ddd65520a885e26e8b0767
