### ISSUE TITLE
should CLI automatically switch env on account switch?

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/cli#395]
Switching users is annoying IMO. The CLI says that I am not able to use some environment anymore, and suggests to switch it, but I think, it should just do it for me. 

```
$ swarm login
Username or email: zyndiecate
Password:
Login Succeeded
Warning: Your current environment "test/dev" is no longer accessible.
Use the 'swarm env' command to change it. For example:

  swarm env zyndiecate/dev

```

Currently I need to do the extra step every time by myself.

```
vagrant@vivid64 $ swarm env zyndiecate/dev
Environment zyndiecate/dev has been selected
```

What do you think? Would that makes sense? are there cases where a user switches accounts and does not want to switch the environment?

**Comment by marians** [comment]
You're right, we should try to avoid the extra step. I think:

- if `<username>/dev` is in fact available (which I hope we can find out), we should automatically switch to that environment.
- if not: We could create `<username>/dev` and switch to it or display the message as it is right now. No strong preference.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
