### ISSUE TITLE
Providing the wrong component prints an unhelpful "Wrong Input." message

### ISSUE THREAD

**Issue by ZeissS** [giantswarm/cli#399]
```
swarm update --strategy=hot-swap database/mysql
Updating component 'database/mysql' with version 'latest' and strategy 'hot-swap'...
Wrong Input.
```

Here, the user forgot that he has to provide the service-name besides the component name (so there is a service e.g. called `mysql` which has a component named `database/mysql`). Since no component could be found, the API returns `wrong input`. The message printed by the CLI could be more helpful here.

**Comment by ZeissS** [comment]
ping @marians

**Comment by marians** [comment]
Here is my suggestion to handle this case properly.

```
No component found for 'database/mysql'. Service 'database' is not known.
Please provide a valid component name in the format <service_name>/<component_name>. Use --help for details.
```

Labelling backlog.

**Comment by ZeissS** [comment]
This was also "improved" a bit by https://github.com/giantswarm/client-go/pull/83
