### ISSUE TITLE
Have release notes available in the CLI

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#40]
Idea from the gitter channel. Dirk recommended to have a changelog within the cli.

This could help users to find new features within the cli _and_ on the cluster.

Original Author: @teemow
Created at 02-12-2014 20:52:02
Gitlab: [giantswarm/cli!156](https://git.giantswarm.io/giantswarm/cli/issues/156)

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
