### ISSUE TITLE
implement proper "wait for" when updating service definition

### ISSUE THREAD

**Issue by zyndiecate** [giantswarm/cli#404]
Because of the complexity of service definition updates, it is quiet hard and not fully solvable to implement what we really want and need. Imagine you have 6 steps during an update.
- 2 steps to add something.
- 2 steps to update something.
- 2 steps to remove something.

After each block of steps (one block is related to: add, update, remove), the status will be UP. We would need to ensure that the status for a given time is the same, but I really don't like that. So what to do? Again, I refer to the upcoming task API.

See https://github.com/giantswarm/cli/pull/402#discussion-diff-39397046

**Comment by ZeissS** [comment]
+1 for fixing this properly with the task api

**Comment by zyndiecate** [comment]
This is already done.
