### ISSUE TITLE
give proper feedback in case of using a v1 swarm.json

### ISSUE THREAD

**Issue by ewoutp** [giantswarm/cli#408]
See https://github.com/giantswarm/cli/pull/406#discussion_r39724262

**Comment by marians** [comment]
Do we recognize when a user submitted a valid V1 service definition? I assume we don't, in which case the message can only be very generic. Something like "Please provide a valid Service Definition" (+reference URL).

If we can in fact recognize a V1 app, the message could be more specific, like "The definition format used is no longer supported. ..."

**Comment by ewoutp** [comment]
We no longer recognize V1 definitions.

**Comment by marians** [comment]
Then we'll have to go with case A. I bet there already is a generic message for an invalid JSON definition, right? We'd have to use this then. Or I don't understand the purpose of this issue.

**Comment by ewoutp** [comment]
Now we get this:

```
Validation error: invalid service definition, expecting valid types of V2GiantSwarm
```

Doesn't really look nice to me.

**Comment by marians** [comment]
How about this:

```
The provided service definition (<name of file parsed>) is not valid. Please refer to the service definition reference for details:

    https://docs.giantswarm.io/reference/swarm-json/

```

Mind the extra blank line at the end for multi line messages.

**Comment by ZeissS** [comment]
Closing, as v1 is not supported in our code anymore. We can't identify it anymore.
