### ISSUE TITLE
`swarm logs` should give a message if no logs are found

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#41]
Currently `swarm logs` doesn't give any output if there are no logs 'yet'. This could also be an error or confusing for the user.

So maybe we add a 'header' like journalctl does:

```
-- Logs begin at Mon 2014-12-01 11:00:59 UTC, end at Mon 2014-12-01 13:02:52 UTC. --
```

Adding this to all log output would help the user to identify since when there where the messages shown to him (or not).

Original Author: @teemow
Created at 01-12-2014 13:06:13
Gitlab: [giantswarm/cli!149](https://git.giantswarm.io/giantswarm/cli/issues/149)

**Comment by marians** [comment]
This is ready for implementation and should be rather fast and easy to do.
