### ISSUE TITLE
New version notice should only appear when STDOUT is an interactive terminal

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#412]
To prevent the "A new CLI version is available" notice from appearing in a script environment, we should check if the current STDOUT is an interactive terminal.

Ping @luebken

**Comment by ewoutp** [comment]
I would also like to suppress the version check with a command line flag.

**Comment by marians** [comment]
@ewoutp Do you want to share the rationale behind your wish?

**Comment by ewoutp** [comment]
I found myself needing this when using `swarm migrate` on an older cli version (in a docker container).

I was explicitly using an older version of the CLI and since I did not not anything network related I did not care about the version check (was just unwanted output).

Now I know that we no longer have the migrate command, but I'm sure some similar situation will popup in the future.

**Comment by luebken** [comment]
Begs the question if we should just use the command line flag. How are other tools doing this?

**Comment by ewoutp** [comment]
> How are other tools doing this?

I've seen everything from no version checking, to always version checking (like we have now), to only check in `version` command etc.

As a privacy sensitive person, I always wonder why apps want to send a request to a server when you;re only doing something local (like the former `swarm migrate`).

**Comment by marians** [comment]
> to always version checking (like we have now)

Actually it was supposed to happen once a day, if I remember correctly. Plus whenever you call `swarm version`, which still makes total sense to me.

**Comment by ewoutp** [comment]
> Actually it was supposed to happen once a day,

That is the case, I was a bit "short" in my text.

**Comment by marians** [comment]
https://github.com/giantswarm/cli/issues/420 is soon to be closed, so we can implement the suppression on dumb terminals.
