### ISSUE TITLE
Internal server errors should trigger a non-zero exit code.

### ISSUE THREAD

**Issue by ZeissS** [giantswarm/cli#413]
One of our customers ran into this. The API returned an internal server error, but the swarm cli had an exitcode of 0.

**Comment by ZeissS** [comment]
ping @ewoutp

**Comment by ewoutp** [comment]
Do which know which command was used?

I checked, when calling `Quitf` (uses to show errorr) we do an `os.Exit(1)`

**Comment by ZeissS** [comment]
`swarm update` - Since an client warning appeared, sthg before 0.21.0

**Comment by ewoutp** [comment]
As far as I can tell we already exit with code 1.

**Comment by ZeissS** [comment]
similar to #384 - closing for now as the customer and us suspected its the wrapping bash script that loses the error, not the cli. the code looks good.
