### ISSUE TITLE
swarm exec doesn't allow to navigate command history in some containers/shells

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#415]
A user reports that when being in an interactive shell session via `swarm exec`, it's not possible to use the arrow keys to move the cursor or navigate the command history.

I can reproduce this with a redis container and `/bin/sh`.

**Comment by cpoepke** [comment]
I used bash and a debian Docker Containter

**Comment by marians** [comment]
I just tested using the official `debian:latest` image. There I can navigate the history using the error keys, just as I'm used to. In `redis` with `bin/sh` it still shows the problems described above.

So this obviously depends on the configuration of the image/container/shell.

**Comment by zyndiecate** [comment]
Can we close this issue then?

**Comment by cpoepke** [comment]
Sure
