### ISSUE TITLE
'Wrong Input.' error when scaling down is not allowed

### ISSUE THREAD

**Issue by zyndiecate** [giantswarm/cli#425]
I have some service running and its component is scaled 5 times. When I want to scale it down I just get `Wrong Input.`. We can do better. Reason here is that I defined a minimum scale of 3, so I am not allowed to scale down to 1. The error should reflect that to help the user. Note, I am pretty sure this applies to scaling up as well.

```
$ swarm scaledown redis-example/web 4
Scaling down component redis-example/web by 4...
Wrong Input.
```

**Comment by marians** [comment]
Duplicate of #244, it seems
