### ISSUE TITLE
Cosmetic change in 'swarm delete' output

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#428]
```Deleting service helloworld ...```

should become

```Deleting service 'helloworld'…```

That's single quotes around the service name. And note that the three dots at the end are one character, not three. And there is no space before the dots.

Ping @ewoutp

**Comment by ewoutp** [comment]
I think there are more places where we use 3 dots. I'll change those as well.

**Comment by ewoutp** [comment]
Done in #421
