### ISSUE TITLE
swarm exec shouldn't suffer from connection timeouts

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#429]
A user reports that timeouts after 30 seconds can happen with `swarm exec`.

**Comment by decoomanj** [comment]
+1

**Comment by luebken** [comment]
@ewoutp what is your take on increasing the timeout for `swarm exec`?

**Comment by ewoutp** [comment]
I'm surprised by the 30s, but not by the timeout itself. There is no explicit timeout in the software set.
If nothing is happening, then there is no data being send over the wire and everything in between the container and the CLI may think the connection is dead and terminate it (which is of course wrong but happens).

To solve this properly we need to extend the wire protocol to keep sending `ping` messages similar to what is being done in websockets. I would vote to switch completely to a websocket based protocol.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
