### ISSUE TITLE
What to do with long-running tasks which never end?

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#432]
In theory, we can now have the client wait for a task to be finished for a very long time, if something gets stuck in the backend.

Do we want to finish waiting at some point? And if yes, how do we help in this situation to solve the problem?

**Comment by ewoutp** [comment]
Most tasks that wait have a timeout.
There is an exception when you're using `signal_ready` in your definition. In that case you will still have a timeout, but it is VERY long.

When a task expires (is not finished before the expiration date), the task is finished with a timeout error.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
