### ISSUE TITLE
'swarm info' should reveal API endpoint details

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#436]
Story: As a user, I want to get all relevant context information when calling `swarm info`.

This is how `swarm info` can look, currently:

```
Cluster status:      reachable
Swarm CLI version:   0.22.1+git
Logged in as user:   marian
Current environment: marian/dev
```

There are issues with this:

- We don't display the API endpoint. In case an environment variable (`SWARM_ENDPOINT_URL `) or the `--api-endpoint` flag is used, which might be the case when using an alias for `swarm`, the user could use a non-default API endpoint without knowing. We should make it possible to discover this here.

- We don't show which cluster the user is connecting to. We say it's reachable (or not), but we dno't show which one. As above, there could be an environment variable effective on the user's side (`SWARM_CLUSTER_ID`) or the server-side configuration based on the organization might affect this. So in order to understand what's actually going on, we need to output this here.

- The order is odd. The cluster ID can actually change based on the organization, so the "Cluster status" being in the top row isn't ideal.

We decided first to hide these facts since we thought that users wouldn't need to think about this. It turns out that this is no longer true with more dedicated and on-premise customers.

Here is a proposed fix:

```
Swarm CLI version:   0.22.1+git
Logged in as user:   marian
API endpoint:        https://api.giantswarm.io
Current environment: marian/dev
Cluster ID:          aws-alpha.giantswarm.io
Cluster status:      reachable
```

The order of information display follows an implicit hierarchical logic:

1. CLI version is at the top, since this isn't affected by anything else but the software the user installed.
2. The current user name is second. This is also not affected by anything else but a user's decision.
3. The API endpoint defines the context on the topmost level, so it comes next.
4. The currently selected org and env (=environment) has to be known in the selected API context and it influences (unless overridden) the cluster to be used
5. The currently selected cluster ID. It comes as a result of the env selection above or a direct setting.
6. The cluster status refers to the cluster mentioned one line above.

There is an issue https://github.com/giantswarm/cli/issues/273 about which cluster to ping. With the specs above, it's obvious to me that we need to ping exactly the cluster displayed in the row above.

**Comment by zyndiecate** [comment]
Thanks for taking care. What I have in mind:
- AWS alpha is public (`aws-alpha.private.giantswarm.io` -> `aws-alpha.giantswarm.io`)
- I know there is a need for all this information, but having this is not sexy. It is too much. The product should be easily usable and understandable, as easy as possible. 
  - There should only be one API endpoint. 
  - There should not be something like a cluster ID known to the user. We should rather map this based on username and environment. AFAIK we are doing this, so why is it necessary for the user to know which cluster ID he uses?

**Comment by marians** [comment]
@zyndiecate Thanks. I edited out the `.private` in order not to promote false information here.

"Only one API endpoint" is already no longer true, with on-premise installs.

In the current transition of alpha clusters, we already see that the cluster ID is relevant. Also, what if a user who is on dedicated by default wants to also run something on the shared cluster? In fact the cluster ID exists and has an impact.

I think we don't impair the usability by adding this information.

**Comment by hectorj2f** [comment]
We have to encapsulate this information into simple cluster names without specifying `aws-alpha` or `leaseweb-alpha`, `leaseweb-neofonie`.

**Comment by ZeissS** [comment]
We could probably change our model to have an abstract clustername and the DNS entry is looked up.

**Comment by marians** [comment]
OK, let's leave out the cluster ID, since it's controversial/problematic. I changed the title accordingly.

Here is a PR that does the re-ordering and that also integrates showing the API endpoint:
https://github.com/giantswarm/cli/pull/442

**Comment by marians** [comment]
Regarding showing the cluster ID, here is a new proposal:

Let's show the cluster ID if it is set. If it isn't set (which is the default), we don't show the line at all.

This way it's made visible when the user (which is mainly ourselves, but possibly also on-premise customers) has tweaked something locally.

**Comment by marians** [comment]
Closed by https://github.com/giantswarm/cli/pull/466
