### ISSUE TITLE
Is test.sh still needed?

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#449]
What is 

https://github.com/giantswarm/cli/blob/master/test.sh

used for? The service definition in there is outdated.

**Comment by marians** [comment]
Ping @ewoutp @zyndiecate

**Comment by zyndiecate** [comment]
IMO this can be carried to the museum.

**Comment by marians** [comment]
What about the mentions in [Makefile](https://github.com/giantswarm/cli/blob/master/Makefile)?

**Comment by ewoutp** [comment]
It is still used by the `run-test-apps` target. 
But we hardly use that. We need to think about which direction to go with it

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
