### ISSUE TITLE
Access to logs of multiple instances/components at the same time

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#45]
From a user perspective it would help to aggregate logs for services/components and even the entire app.

It should be clear for every line in the log what the source of that line is.

@denderello @zeisss @luebken  Please comment on how you should think it should look.

@denderello @zeisss Please comment on how to implement it (where)

Original Author: @ewout
Created at 28-11-2014 11:01:35
Gitlab: [giantswarm/cli!139](https://git.giantswarm.io/giantswarm/cli/issues/139)

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
