### ISSUE TITLE
Improve usage of local flags

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#46]
Several commands have local flags (like `swarm start --detach app`) but there is no proper place to document their usage.

Right now all flags are included in each usage line which looks overkill.

@marian Please suggest a proper format

Original Author: @ewout
Created at 27-11-2014 10:03:53
Gitlab: [giantswarm/cli!137](https://git.giantswarm.io/giantswarm/cli/issues/137)

**Comment by marians** [comment]
I will check this with the current CLI

**Comment by marians** [comment]
Looks to me as if we do an okay job of explaining local variables in the current incarnation. Closing.
