### ISSUE TITLE
Continue waiting for a task after Ctrl-C in swarm.

### ISSUE THREAD

**Issue by ewoutp** [giantswarm/cli#464]
I often find myself doing a swarm command that generates an asynchronous task and then kill swarm when it is waiting for that task to finish (doing that because it can take longer than expected).
Typically I then perform a `swarm status` and I would like to re-continue waiting for the task to finish.
That is currently not possible.

I think it would be nice if `SIGTERM` is caught during the `WaitForTask` period and if caught, print a command how to continue waiting for that task to finish. (the same command should be printed when I add the `--detach` flag to the swarm command).

Of course this implies that we have a swarm command to wait for a task.

**Comment by ewoutp** [comment]
@marians Any thoughts on this?

**Comment by marians** [comment]
If I get it right, you are saying _As a user, I want to exit a blocking CLI command so that I can resume waiting for this commands outcome at any time using a special command._

I see a use for this, but it feels very sophisticated. I would consider this if other users would support the idea.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
