### ISSUE TITLE
`swarm create`: Service definition validation should take current environment into consideration

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#47]
Following scenario:

- User is in environment "user/myenv"
- swarm.json uses variables
- swarmvars.json has keys for some environments, but not for "user/myenv"

The user issues `swarm create swarm.json`. The following output is produced:

```
Invalid image part "$docsauth_image": Not a valid docker image. Format: [<registry>/]<repository>[:<version>]
```

(This actually refers to the content the docs [swarm.json](https://git.giantswarm.io/giantswarm/docs/blob/master/swarm.json) file.)

The actual problem here is that the variable "$docsauth_image" cannot be resolved because in swarmvars.json there is no entry for the current environment user/myenv.

For the case that swarm.json contains variables and swarmvars.json (or the respecitve vars file) is read, I guess it would be trivial to add an explicit check if the current environment is contained. If not, the following error message can be printed and no further action should be taken:

```
Your selected environment 'user/myenv' is not configured in the file 'swarmvars.json'. The application could not be created.
```

Original Author: @marian
Created at 27-11-2014 09:13:43
Gitlab: [giantswarm/cli!135](https://git.giantswarm.io/giantswarm/cli/issues/135)

**Comment by marians** [comment]
The essence of this issue is now kept more concrete in #21 and #486, so I'm closing this one.
