### ISSUE TITLE
Allow user to download files from an instance

### ISSUE THREAD

**Issue by oponder** [giantswarm/cli#470]
I wanted to copy a database backup to my local machine quickly and naively tried something like:
`swarm exec instance_id -- cat backup.tar.gz > ~/Desktop/dump.tar.gz`

That didn't work, the file came accross but something went wrong because it was about 20 bytes larger than it should be.

Some official way to get files from an instance to my local machine would be nice! Kind of like: http://docs.docker.com/engine/reference/commandline/cp/

ping @ewoutp

**Comment by marians** [comment]
Related, but not identical: https://github.com/giantswarm/cli/issues/152

**Comment by ewoutp** [comment]
You can use `swarm exec` for it, but you have to base64 encode it and decode it after the data has been received. BUT this will not work for larger files.

So the request is very valid.

**Comment by marians** [comment]
I changed the title to "Allow user to download files from an instance" to have a feature request that talks more about the actual problem the user would want solved, and not about implementation ideas.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
