### ISSUE TITLE
Copying files to local machine using `swarm exec cat` stdout redirection doesn't work

### ISSUE THREAD

**Issue by oponder** [giantswarm/cli#471]
Running this: `swarm exec instance_id -- cat backup.tar.gz > ~/Desktop/dump.tar.gz`

Results in a file that is 20 bytes larger on my desktop than the actual file in the instance.

ping @marians, @ewoutp 

related: https://github.com/giantswarm/cli/issues/470

**Comment by marians** [comment]
I suggest we test this with a file that's easy to debug next.

**Comment by ZeissS** [comment]
See also #250

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
