### ISSUE TITLE
Running 'exec'  on instance that is down creates wrong feedback

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#476]
I have an instance with the ID `l218b9nwt3b7`, which is `down`. Then I execute this

```
swarm exec l218b9nwt3b7 -- ps -a
```

This is the output:

```
Command executed, no output has been generated.
```

The expected output would be something like

```
Error: 'swarm exec' requires an instance to be up. Instance 'l218b9nwt3b7' is down.
```

**Comment by marians** [comment]
Smells like we would ideally need

- either a specific error from the API route `/v1/org/{org}/instance/{instance}/exec´ for "instance is not up"
- or an API and client-go method to fetch the status of one specific instance

**Comment by zyndiecate** [comment]
Reopening for PDV :)

**Comment by marians** [comment]
Validated this recently. All fine :)
