### ISSUE TITLE
Can't delete an env: Environment 'gsdemo/bigexample' not found

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#478]
The API call `GET https://api.giantswarm.io/v1/org/gsdemo/env/` shows this output:

```
{"status_code":10000,"status_text":"success","data":{"environments":[{"name":"bigexample"}]}}
```

But when trying to delete the env `gsdemo/bigexample`, this happens:

```
$ lwswarm env -d gsdemo/bigexample
Environment 'gsdemo/bigexample' not found
```

`lwswarm` is:

```
alias lwswarm='SWARM_CLUSTER_ID=leaseweb-alpha-private.giantswarm.io swarm --config-dir=/Users/marian/.leasewebswarm'
```

**Comment by zyndiecate** [comment]
I wanted to check that. I have no access to the environment. Locally adding/removing environments works. Don't know if this is borked because of the API migration. 

- What does `lwswarm env -l` show? 
- Can you add environments to this org? Can you remove them?
- What do the API/companyd logs say?

**Comment by zyndiecate** [comment]
I vote to close this issue. No information. No response. Feel free to reopen if necessary.
