### ISSUE TITLE
We should retry waitfor() on connection-reset-by-peer

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#479]
On leaseweb-alpha:

```
$ swarm start graphhopper-cgn
Starting service 'graphhopper-cgn'…
Waiting for 'graphhopper-cgn' to get started…
Get https://api.giantswarm.io/v2/org/marian/env/dev/task/xqakngx1p5nz3je3/waitfor: read tcp 178.162.217.222:443: connection reset by peer
```

This was 44 minutes after issuing the command.

**Comment by marians** [comment]
The underlying issue causing the long `swarm start` runtime: https://github.com/giantswarm/user-support/issues/88

**Comment by zyndiecate** [comment]
What is this issue about? What do we need to fix here? I am a little bit lost on the description.

**Comment by ZeissS** [comment]
IMHO we should simply retry the `/waitfor` call when a `connection reset by peer` occurs.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
