### ISSUE TITLE
Definition update of "image" not working together with "placement": "one-per-machine"

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#480]
A customer has tried the following service definition update:

```
Updating service 'myservice' according to 'swarm.json' will apply the following changes:

--------------------------------------------------------------------------------

Modify 3 components
  celery
    Definition changes
      image    value will change to    registry02.giantswarm.io/org/myservice-celery:latest

  celerybeat
    Definition changes
      image    value will change to    registry02.giantswarm.io/org/myservice-celerybeat:latest

  django
    Definition changes
      image              value will change to    registry02.giantswarm.io/org/myservice:latest
      scale.placement    value will change to    one-per-machine

--------------------------------------------------------------------------------

```

Result:

```
wrong input: wrong input: cannot update to the same image version 'latest' when
using scaling placement one-per-machine
```

Is there a good reason why theses changes should not work together? I'd expect this to work, and clearly our users do so, too.

**Comment by marians** [comment]
Ping @zyndiecate

**Comment by zyndiecate** [comment]
See https://github.com/giantswarm/app-service/blob/master/service/app-service/update_component_tasks.go#L172

This is due to the fact that we need a reliable way of creating conflict groups for the "one-per-machine" placement feature. To create this conflict group hash we also use the version of an instance. So this is an expected behavior, so the issue can be closed. 

This problem would not occur if people would use proper tags and not over and over again this shitty `latest` tag. We should advice customers to not do that. 

Question is if we really need the version to build the conflict group hash. @ewoutp any ideas?

**Comment by marians** [comment]
This doesn't make any sense from a user perspective and it's definitely nothing I would call "expected behaviour". Leaving it open so we can come up with a better solution.

**Comment by zyndiecate** [comment]
It is expected in terms of implementation.

**Comment by ewoutp** [comment]
There is no simple way to leave out the image version in the generation of the conflict group.
A solution for this can be that we find the best update strategy when doing a service update.
We already have an issue with service updates regarding volumes and we should add this to it.

**Comment by marians** [comment]
In simple fix would be to tell the user immediately, before presenting the update plan, that the intended update won't work.

**Comment by marians** [comment]
Even more confusing is the fact that as a user I can have a component with `image` without tag _and_ `placement: one-per-machine` and it seems to work just fine. So no tag works, `latest` doesn't.

**Comment by zyndiecate** [comment]
> So no tag works

IMO it should not. Seems like a bug.

**Comment by marians** [comment]
Another case how this occurred: `wrong input: wrong input: cannot update to the same image version 'logging' when using scaling placement one-per-machine`

So here the user had the image tag "logging" in use.

**Comment by zyndiecate** [comment]
It doesn't matter which image he uses. It matters that an image is used twice.

**Comment by zyndiecate** [comment]
IMO this is a bad practice.

**Comment by ewoutp** [comment]
+1 on the bad practice.

However people will still use it, so we should fine a way to support service updates in this case.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
