### ISSUE TITLE
Service definition updates shows update plan header too early and in wrong cases

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#481]
Seems like we print the message `Updating service 'myservice' according to 'swarm.json' will apply the following changes:` too optimistically. It's even printed when the command shows a validation error.

```
Updating service 'myservice' according to 'swarm.json' will apply the following changes:
Cannot update service due to a validation error.

    invalid service definition: invalid format for domains: Port must be a number, got 'somsstring': strconv.ParseInt: parsing "somestring": invalid syntax
```

We should make sure that message only appears when the validation succeeded.

**Comment by zyndiecate** [comment]
This issue is no longer reproducable and once https://github.com/giantswarm/cli/pull/512 is merged it should be completely fixed with nice error messages.

**Comment by marians** [comment]
Moved to PDV

**Comment by marians** [comment]
Moved back to review, waiting for #526
