### ISSUE TITLE
missleading state changes during updates

### ISSUE THREAD

**Issue by xh3b4sd** [giantswarm/cli#483]
When I update a service, there is a lot of movement. Components are getting down, comming up, being removed. You get the picture. The thing is, when I am in the middle of such an update process, I expect the service to be up most of the time. Currently we are generating the state based on the accumulated component states. So when a component is down, the whole service is considered down. This is actually not true in the described case. My service is up, but the service state is flapping back and forth. We should fix that.

**Comment by marians** [comment]
@zyndiecate On which cluster have you observed this? Local?

I have recently recorded this behaviour in an app-service issue, including video:
https://github.com/giantswarm/app-service/issues/609

**Comment by zyndiecate** [comment]
I saw this local. This behaviour is cluster independent.

**Comment by marians** [comment]
CC @teemow - We discussed this yesterday. Seems not limited to our live systems.

**Comment by teemow** [comment]
Yes. I am showing fleet during my demos. So the underlying behaviour is correct, but the way we display the status is the problem.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
