### ISSUE TITLE
Context variable replacement is ambiguous: GIANTSWARM_ENV(IRONMENT)

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#498]
We support the use of certain predefined variables which are replces by the app-service with the according values on service creation.

A user reported a problem with this.

> if i try to use `$GIANTSWARM_ENVIRONMENT` in a swarm definition file i end up with a value like `mapleapps/stagingIRONMENT`, because it conflicts with `$GIANTSWARM_ENV`

Obviously the order in which we parse these variables is bad.

Original issue: https://github.com/giantswarm/user-support/issues/59#issuecomment-159631891

**Comment by JosephSalisbury** [comment]
^ ignore: me putting in the wrong url
