### ISSUE TITLE
Interactively generate new service definition ("swarm scaffold")

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#51]
Reasoning: I want the developer to create their first app as fast as possible. It's more an onboarding task. Than a power user task. The current feedback from devs: I didn't have the time. I want them up and running while I am demoing the app.

e.g. 3 commands to get currentweather running:

```
$ swarm login
...
$ swarm create currentweather
Created your copy of the currentweather example
$ swarm up
 ... some sophisticated status update ...
```

Original Author: @luebken
Created at 20-11-2014 16:07:17

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
