### ISSUE TITLE
Alias `swarm rm` with `swarm delete`

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#514]
@JosephSalisbury wants to save time and headaches by using a common shortcut (muscle memory) :)

**Comment by ewoutp** [comment]
We do not have alias aliases so far. I'm fine when we want them, but let's make a clear decision about it.
@marians Your call I guess

**Comment by marians** [comment]
No urgency. This is a place to collect feedback in specific and on general.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
