### ISSUE TITLE
Add activity tracking headers to API calls

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#520]
Regarding usage tracking, when https://github.com/giantswarm/giantswarm/issues/421 is implemented, we need to push the source command and an activity name via HTTP headers.
- source command: The original command line
- activity name: Strings defined by us, e. g. "update-component"

**Comment by ewoutp** [comment]
Implemented in 

https://github.com/giantswarm/cli/pull/534
https://github.com/giantswarm/api/pull/202
https://github.com/giantswarm/client-go/pull/95

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
