### ISSUE TITLE
'swarm start' dies after 2,5 hours, fleet server unable to communicate with etcd

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#524]
The attempt to start a component in a service on aws-alpha resulted in this after 2 hours and 28 minutes:

```
swarm start flighttracking/mongodb
Starting component 'flighttracking/mongodb'…
Waiting for 'flighttracking/mongodb' to get started…
retry limit reached (5/5): googleapi: Error 503: fleet server unable to communicate with etcd
```

The log entries for that error must be somewhere here:

https://kibana.monitoring.giantswarm.io/#/discover?_g=(time:(from:'2015-12-08T16:53:46.941Z',mode:absolute,to:'2015-12-08T17:31:49.764Z'))&_a=(columns:!(logtext),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'logtext:%22fleet%20server%20unable%20to%20communicate%20with%20etcd%22')),sort:!('@timestamp',asc))

There is no related task information to be found using swarmctl.

**Comment by marians** [comment]
Ping @zeisss - In case you still want to take a look while the data is still there.

**Comment by zeisss** [comment]
@marians org, environment please

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
