### ISSUE TITLE
Component update without version argument fails, CLI assumes service update

### ISSUE THREAD

**Issue by marians** [giantswarm/cli#527]
User @luebken tried to update a component with the `latest` version of the image using this command:

```
$ swarm update currentweather/webserver
```

and got this output:

```
stat currentweather/webserver: not a directory
```

There was a `swarm.json` file in the current directory. Also a `currentweather` service was running in the current environment and the `webserver` exists.

The error seems to occur when testing of the first argument (here `currentweather/webserver`) points to a service definition file, in order to then proceed with a service definition update. The CLI should be able to take the error when trying to access the path as a sign that the command should be interpreted as a component update.

**Comment by marians** [comment]
Current workaround for users: Please always use the version argument, which should normally default to `latest` when omitted. Example:

```
$ swarm update currentweather/webserver latest
```

**Comment by luebken** [comment]
Food for though: How about making version mandatory. This makes it explicit and using version numbers is a good pattern anyway for rolling back and forth.

**Comment by marians** [comment]
Trying to reproduce. I have a service `busywait` in my current env with a component `box`.

This happens when I have a directory `./busywait/box` and do `swarm update busywait/box`: 

```
Given config file is a directory: busywait/box
```

And if `./busywait/box` is an empty file:

```
Cannot parse service definition: unexpected end of JSON input
```

I am leaning towards closing this, since it appears not reproducible, and also there is a viable workaround.

**Comment by luebken** [comment]
+1

**Comment by marians** [comment]
We could reproduce it last friday when there was a file called `currentweather` (the compiled Go binary) in the current directory.
