### ISSUE TITLE
Allow for YAML service definition

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#54]
As indicated by alpha user *******, JSON is a complicated configuration file format, compared to YAML.

This might be a case of personal preference, but I have sympathy for the suggestion.

Original Author: @marian
Created at 11-11-2014 09:09:56
Gitlab: [giantswarm/cli!109](https://git.giantswarm.io/giantswarm/cli/issues/109)

**Comment by marians** [comment]
We made progress on the open sourcing part :)

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
