### ISSUE TITLE
Print out rendered `swarm.json` on error of `swarm update`

### ISSUE THREAD

**Issue by webwurst** [giantswarm/cli#540]
We saw this error today:
```
invalid service definition: invalid format for domains: Port must be a number, got '[...]': strconv.ParseInt: parsing "[...]": invalid syntax
```
The corresponding `swarm.json` looked fine though contained some `$VARIABLES`.

It would be cool if `swarm --debug update` prints out the rendered current and new definitions to make debugging easier.

**Comment by marians** [comment]
> It would be cool if swarm --debug update prints out the rendered current and new definitions to make debugging easier.

This suggetsion is covered by https://github.com/giantswarm/cli/issues/486

@webwurst If this issue should be kept open, please rephrase and add some information on how to reproduce the problem. Thanks!
