### ISSUE TITLE
swarm exec fails to stream tail output

### ISSUE THREAD

**Issue by zeisss** [giantswarm/cli#541]
On a container with an apache2, I did a `swarm exec <id> -- tail -f /var/log/apache2/access.log` but not updates were sent. Aborting and reexecuting showed that there were updated to the file.

**Comment by marians** [comment]
I'll do what's your job normally, @zeisss: Which cluster? Some more information that would help reproducing this?

**Comment by zeisss** [comment]
This was `aws-alpha` and `leaseweb-alpha` in the apache2 container of a customer. Haven't tried reproducing this yet.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
