### ISSUE TITLE
`swarm ls --all` dies with `Access denied` even if access for some services is valid

### ISSUE THREAD

**Issue by webwurst** [giantswarm/cli#544]
`swarm ls --all` should iterate over "all services in all available environments" and print out state individually for each.

**Comment by zeisss** [comment]
According to #aws-shutdown-party we haven't changed the aws companies on purpose.

**Comment by zeisss** [comment]
We have fixed a bunch of accounts ( ~50 or the 700) to use leaseweb now. Its unclear to me what should happen to the others.

**Comment by zeisss** [comment]
This is not a cli bug, but a misconfiguration server-side.
