### ISSUE TITLE
go get failed referencing giantswarm/container-states 

### ISSUE THREAD

**Issue by henrjk** [giantswarm/cli#549]
I am getting an error when trying to `go get` this project:

``` 
$ go get github.com/giantswarm/cli
# cd .; git clone https://github.com/giantswarm/container-states /home/dev/go/src/github.com/giantswarm/container-states
Cloning into '/home/dev/go/src/github.com/giantswarm/container-states'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/giantswarm/container-states/v1: exit status 128
```

I noticed that there is a more elaborate way to build this, so perhaps this is expected. 

See also #538

**Comment by zeisss** [comment]
Thanks for this @henrjk. We will check it out. Sorry for not coming back to you earlier.

**Comment by zeisss** [comment]
@henrjk Hey there. We have made the missing repository open-source and changed the Makefile to be more noisy if we do this again by using https everywhere. Can you try again and verify it works for you?

**Comment by henrjk** [comment]
@zeisss Thanks for looking into this.

I am seeing this now:

```
$ go get github.com/giantswarm/cli
# github.com/giantswarm/cli/create
go/src/github.com/giantswarm/cli/create/create.go:60: undefined: userconfig.ParseServiceDefinition
$
```

**Comment by zeisss** [comment]
Are you using the Makefile or try to build manually?

**Comment by henrjk** [comment]
I am not using the Makefile yet. 

However I just tried a new go workspace and now the go get worked for me. So everything looks good to me regarding this issue.

**Comment by henrjk** [comment]
Thank you!

**Comment by zeisss** [comment]
You are welcome!
