### ISSUE TITLE
swarm open should open an app in the browser

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#55]
As recommended by _a user_ in our alpha channel it would be handy to have a `swarm open` command that opens up the url of the app in the browser. Similar to `heroku open`.

See: https://devcenter.heroku.com/articles/getting-started-with-rails3#visit-your-application

Original Author: @teemow
Created at 10-11-2014 16:20:21
Gitlab: [giantswarm/cli!106](https://git.giantswarm.io/giantswarm/cli/issues/106)

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
