### ISSUE TITLE
image name validation is broken: registry.giantswarm.io/some-org/serv is invalid

### ISSUE THREAD

**Issue by Nesurion** [giantswarm/cli#554]
`registry.giantswarm.io/some-org/serv` is a valid image name, at least docker is fine with it. The cli however complains, that it is invalid.
renaming `registry.giantswarm.io/some-org/serv` to `registry.giantswarm.io/someorg/serv` works.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
