### ISSUE TITLE
Status aggregation for an app needs thought (`swarm status`)

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#58]
We should clarify and maybe re-think how the displayed status for an app is aggregated based on the individual component (and instance) statuses.

Currently,

* an app is regarded "failed" if at least one component is failed.
* an app is "up" if all components are up.

This means that, for example, an app is regarded "starting" when some component on some instance is currently "starting". And it's failed if only one component is failed, even if this component is "up" on a different instance.

I have doubts that this is really useful. Would like to investigate this with user feedback to verify and, if necessary, come up with an alternative.

Ping @luebken

Original Author: @marian
Created at 09-11-2014 11:14:38
Gitlab: [giantswarm/cli!94](https://git.giantswarm.io/giantswarm/cli/issues/94)

**Comment by marians** [comment]
Closing for giantswarm/giantswarm#385
