### ISSUE TITLE
Variable passing to `swarm create` should be cleaner

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#60]
Currently variables are passed on the command line like this:

```
$ swarm create swarm.json --var=var1=foo --var=var2=bar
```

The double assignment operator in `--var=var1=foo` makes this look kind of wrong.

ElasticSearch uses this format, where -D probably stands for "define":

```
-Dvar1=foo -Dvar2=value
```

Another alternative I'd like is a colon:

```
--var=var1:foo --var=var2:bar
```

Original Author: @marian
Created at 08-11-2014 15:51:26
Gitlab: [giantswarm/cli!91](https://git.giantswarm.io/giantswarm/cli/issues/91)

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
