### ISSUE TITLE
add tiny cli tutorial

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#69]
Things are complex. To get users into the swarm workflow it would be nice to have a new command like `tutorial`, that introduces a user quickly into basic mechanisms of the `cli`. Just downloading the `cli` binary and executing `swarm tutorial` should wrap up important work flows. That would have the effect of a documentation, but maybe an interactive tutorial would be more efficient. 

@luebken @marian 

Original Author: @zyndiecate
Created at 09-10-2014 22:37:41
Gitlab: [giantswarm/cli!69](https://git.giantswarm.io/giantswarm/cli/issues/69)

**Comment by marians** [comment]
Our ramp-up (Quickstart in docs) after sign-up should be sufficient.
