### ISSUE TITLE
Automatically set environment variable if component has domains configured

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#7]
Story: As a user, I want to use the domain config of my component inside a container.

If a component has one or more domains entries configured, it would be convenient to have them as values in environment variables inside the running Docker container.

Todo:

* Discuss pros, cons, implementation details
* Define naming scheme, especially with regards to the possibility to have multiple domains for a component

Original Author: @marian
Created at 21-01-2015 16:51:54
Gitlab: [giantswarm/cli!243](https://git.giantswarm.io/giantswarm/cli/issues/243)

**Comment by marians** [comment]
Closing this, since we are the only requester. We are solving this by the use of variables in swarm.json.
