### ISSUE TITLE
Human friendly vs. machine readable output

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#71]
Unix CLI tools are frequently used to automate processes, and it would be nice if swarm supported this tradition. However CLI output should also be readable and understandable -- in other words: friendly to the human user.
- What are the best practices here?
- Who sets the benchmark, how do they do it?

In my opinion, human friendlyness should be our priority (read: the default). Machine friendlyness could be activated on demand.

For example, we could introduce a switch that sets the output mode to machine readable. For example, if we use CSV as a standard output format, it could be activated like this:

```
swarm status landingpage -f csv
```

The longer code shouldn't be a problem, since this is something developers write into scripts. It's not typed frequently in the command line.

The output for the command above could look like this:

```
service,component,instanceid,status
static,nginx,962f9eda-966e-480c-8a80-f5a63235801f,up
```

CSV is easily processed with common tools like awk, sed and grep. More advanced output processing can be done using csvkit (pip install csvkit).

Original Author: @marian
Created at 09-10-2014 08:34:10
Gitlab: [giantswarm/cli!65](https://git.giantswarm.io/giantswarm/cli/issues/65)

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
