### ISSUE TITLE
Wrong docker image tag leads status report

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#75]
Failed container is reported as up.

```json
{
    "app_name": "swarmdocs",
    "services": [
        {
            "service_name": "docs-service",
            "components": [
                {
                    "component_name": "docs-auth",
                    "image": "registry.private.giantswarm.io/docs-auth:0.0.1",
                    "ports": [ "80/tcp" ],
                    "dependencies": [{ "name": "upstream", "port": 8000 }],
                    "domains": { "docs.giantswarm.io": "80" }
                },
                {
                    "component_name": "upstream",
                    "image": "registry.private.giantswarm.io/docs",
                    "ports": [ "8000/tcp" ]
                }
            ]
        }
    ]
}

```

Ich habe irrtümlicher Weise docs-auth:0.0.1 auf docs-auth:0.3.0 gehoben. Führt zu keinem Fehler den der Benutzer sehen konnte. Swarm status hat up gemeldet. Obwohl nichts gestartet wurde.

__Translation:__ I have accidentally upped the image version from `docs-auth:0.0.1` to `docs-auth:0.3.0`. This didn't lead to any error being reported. `swarm status` reported `up`, although nothing has been started.

Original Author: @luebken
Created at 22-09-2014 14:25:27
Gitlab: [giantswarm/cli!48](https://git.giantswarm.io/giantswarm/cli/issues/48)

**Comment by marians** [comment]
Needs retesting, assigned to myself

**Comment by marians** [comment]
Tested a component update again with an unavailable image tag. Got the expected error that the component failed to start. Closing.
