### ISSUE TITLE
Allow running of provisioning scripts

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#78]
For STM we needed some kind of provisioning steps:

 * Create a bunch of rabbitmq users
 * Provision school-service with default schools

For non-production envs also:
 * Create a dummy challenge & beneficiary

It would be nice if we could support hooks or something that execute when a component/service/app gets in certain states:
* one instance(group) running
* all instance(groups) running
* instance(group) restarted

Original Author: @zeisss
Created at 09-09-2014 11:57:10
Gitlab: [giantswarm/cli!40](https://git.giantswarm.io/giantswarm/cli/issues/40)

**Comment by marians** [comment]
Stephan says we can close it.
