### ISSUE TITLE
Run a Giant Swarm service locally

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#79]
It would be nice for testing a swarm.json if it could be used with the local docker service.

Original Author: @zeisss
Created at 09-09-2014 11:50:53
Gitlab: [giantswarm/cli!38](https://git.giantswarm.io/giantswarm/cli/issues/38)

**Comment by marians** [comment]
@teemow Can we close this, since we are working on tinyswarm?

**Comment by teemow** [comment]
i'm not sure we are working on "tinyswarm" in that sense. we are working on a way to let ops people run a cluster - not a product that can be used by devs locally.

**Comment by puja108** [comment]
imho we need to clarify our goals on tiny swarm, as they are spreading. This issue could maybe also be solved with some kind of "docker compose compatibility" that we talked about many times.

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
