### ISSUE TITLE
swarm.json validation of "env" struct should warn on duplicate keys

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#8]
I just created an app with a duplicate key within one "env" struct.

```
"env": {
  "BACKUP_INTERVAL": "3600",
  ...
  "BACKUP_INTERVAL": "60"
}
```

This didn't result in a warning or error message.

Since this is hardly intended, I think we should throw a validation error in this case.

Original Author: @marian
Created at 21-01-2015 15:52:11
Gitlab: [giantswarm/cli!242](https://git.giantswarm.io/giantswarm/cli/issues/242)

**Comment by marians** [comment]
Closing in favor of https://github.com/giantswarm/cli/issues/486
