### ISSUE TITLE
Forward local ports to services

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#81]
As a user I want to be able to access my service for configuration/debugging from my computer. Access meaning a port and/or a shell into the container.

For the port forwarding this could work as following:

```
shell1> swarm forward-port <uuid> 80 42000

shell2> telnet localhost 42000
dostuff()
```

`forward-port` would start listening on a local port and forward everything to the destination port of the given instance. It stays open until the user quits (ctrl+c / sigterm etc).

Support for multiple ports would be a nice bonus (maybe separate local and destination port by `:` and allow multiple arguments? `swarm forward-port <uuid> 5672:5672 15672:15672`).

Original Author: @zeisss
Created at 02-09-2014 21:52:08
Gitlab: [giantswarm/cli!34](https://git.giantswarm.io/giantswarm/cli/issues/34)

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.
