### ISSUE TITLE
"swarm user" reports "password changed" when the user has just used the current password

### ISSUE THREAD

**Issue by teemow** [giantswarm/cli#9]
Steps to reproduce:

1. `swarm user -u password`
2. Type current password
3. Type current password again (2 times) as new password

The output now is something like "your password has been changed".

A user reported this as confusing, since the password in fact hasn't changed but remained the same.

Original Author: @marian
Created at 19-01-2015 08:05:34
Gitlab: [giantswarm/cli!239](https://git.giantswarm.io/giantswarm/cli/issues/239)

**Comment by marians** [comment]
Disputable, but very very low severity.
